Workaround for hlint failure
hlint started failing recently:

    src/Xmobar/X11/Text.hs:121:32: Error: Parse error: on input `-'
    Found:
        textExtents (Utf8 fs) s = do
          let (_,rl)  = wcTextExtents fs s
      >       ascent  = fromIntegral $ - (rect_y rl)
              descent = fromIntegral $ rect_height rl + fromIntegral (rect_y rl)
          return (ascent, descent)

It's probably a change in the parser or something, didn't really look
into it, just changed it to something that's parsable.